# Generated by Django 2.0.3 on 2019-05-17 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('dish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Dish')),
            ],
            bases=('orders.dish',),
        ),
    ]
