# Generated by Django 2.0.3 on 2019-05-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_topping_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='small', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='style',
            field=models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], default='Regular', max_length=10),
            preserve_default=False,
        ),
    ]
