# Generated by Django 2.0.3 on 2019-05-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190518_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='order_ID',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_ID',
            field=models.ManyToManyField(blank=True, related_name='boughtby', to='orders.Buyer'),
        ),
    ]
