# Generated by Django 2.0.3 on 2019-05-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190518_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer_ID',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_ID',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, related_name='boughtby', to='orders.Buyer'),
        ),
    ]
