# Generated by Django 2.0.3 on 2019-05-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190518_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer_ID',
            new_name='buyer_id',
        ),
    ]
