# Generated by Django 2.0.3 on 2019-05-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='DishID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='orders.Dish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order'),
            preserve_default=False,
        ),
    ]
