# Generated by Django 2.0.3 on 2019-05-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190518_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer_id',
        ),
    ]
