# Generated by Django 2.0.3 on 2019-06-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_platter_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='style',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], max_length=10),
        ),
        migrations.AlterField(
            model_name='platter',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=10),
        ),
    ]
